return
{
    configurationEnableWindow = false,
    enable = true,
    invertMonsterList = false,
    showCurrentRoomOnly = false,
    showMonsterStatus = true,
    showMonsterID = false,

    mhpEnableWindow = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = false,
    mhpAnchor = 5,
    mhpX = 50,
    mhpY = -65,
    mhpW = 450,
    mhpH = 350,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "",
    mhpNoMove = "NoMove",
    mhpTransparentWindow = false,

    targetEnableWindow = true,
    targetChanged = false,
    targetAnchor = 6,
    targetX = 0,
    targetY = -72,
    targetW = 540,
    targetH = 310,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "NoMove",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = false,
    targetShowMonsterName = true,
    targetShowTechAssist = true,
    targetShowMonsterStats = true,
    targetShowMonsterHP = true,
    targetShowAccuracyAssist = true,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = true,
    targetEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = false,
        chaos = false,
        havoc = false,
    },
}
