return
{
    configurationEnableWindow = false,
    enable = true,
    invertMonsterList = false,
    showCurrentRoomOnly = false,
    showMonsterStatus = true,
    showMonsterID = false,

    mhpEnableWindow = true,
    mhpHideWhenMenu = false,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = false,
    mhpChanged = false,
    mhpAnchor = 5,
    mhpX = 50,
    mhpY = -65,
    mhpW = 450,
    mhpH = 350,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "",
    mhpNoMove = "",
    mhpTransparentWindow = true,

    targetEnableWindow = true,
    targetChanged = false,
    targetAnchor = 4,
    targetX = 0,
    targetY = 10,
    targetW = 540,
    targetH = 400,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "NoMove",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = true,
    targetShowMonsterName = true,
    targetShowTechAssist = true,
    targetShowMonsterStats = true,
    targetShowMonsterHP = true,
    targetShowAccuracyAssist = true,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = true,
    targetEnableActivationRateItems = {
        hell = true,
        dark = true,
        blizzard = true,
        arrest = true,
        seize = false,
        chaos = false,
        havoc = false,
    },
}
